config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root "projects#index"
  post "/projects/pay" => "payment#pay"
  resources :users do
    member do
      get :following, :follower
    end
  end
  resources :projects do
    collection do
      get "search"
      get "apply"
    end

    member do
      get "pay3"
      post "add" => "favorites#create"
    end
  end

  resources :favorites, only: [:destroy]
  resources :relationships

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/course_user.rb
class CourseUser < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/item_user.rb
class ItemUser < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :users, through: :project_users
  has_many :project_users
  belongs_to :user
  # accepts_nested_attributes_for :users
  has_many :favorites
  has_many :users, through: :favorites
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :projects
  belongs_to :users
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :project_users
  has_many :projects, through: :project_users
  has_many :projects
  has_many :favorites
  has_many :projects, through: :favorites
  has_many :active_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :follower, through: :passive_relationships, source: :follower

  def follow(current_user, other_user)
    active_relationships.create(following_id: current_user.id, follower_id: other_user.id)
  end

  def unfollow(current_user, other_user)
    active_relationships.find_by(following_id: current_user.id, follower_id: other_user.id).destroy
  end

  def following?(current_user, other_user)
    current_user.active_relationships.pluck(:follower_id).include?(other_user.id)
  end

  def followings(id)
    relationships = Relationship.where(following_id: id)
    users = []
    relationships.each do |relationship|
      user =  User.find(relationship.follower_id)
      users << user
    end
    users
  end

  def followers(id)
    relationships = Relationship.where(follower_id: id)
    users = []
    relationships.each do |relationship|
      user =  User.find(relationship.following_id)
      users << user
    end
    users
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.new(
        uid: auth.uid,
        provider: auth.provider,
        email: auth.info.email,
        name: auth.info.name,
        # image: auth.info.image
        password: Devise.friendly_token[0, 20]
      )
      user.save
      return user
    end

    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    "/users/sign_in"
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @project = Project.find(params[:id])
    @favorite = Favorite.new(project_id: @project.id, user_id: current_user.id)
    @favorite.save
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    @project = Project.find(@favorite.project_id)
  end

end

app/controllers/payment_controller.rb
require "webpay"

class PaymentController < ApplicationController

  def pay
    # @project_user = Project_user.new(project_id: params[:project_id], user_id: params[:current_user_id])
    webpay = WebPay.new(ENV["webpay_secret_key"])

    if params[:customer_id] == ""
      customer = webpay.customer.create(card: params["webpay-token"])
      user = User.find(params[:current_user_id])
      user.save(customer_id: "customer.id")
      # user.customer_id = customer.id
      # user.save
    else
      customer = webpay.customer.retrieve(params[:customer_id])
    end

    amount = 100

    webpay.charge.create(
      amount: amount,
      currency: "jpy",
      customer: customer.id
    )

    @project = Project.find(params[:project_id])
    if @project.currentprice == nil
      @project.currentprice = 0
      @project.currentprice += amount
      @project.save
    else
      @project.currentprice += amount
      @project.save
    end

    redirect_to :root
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require "instagram"
  require "json"

  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.json {
        render json: { id: current_user.id }
      }
    end
  end

  def search
    @projects = Project.where("title LIKE(?)", "%#{params[:keyword]}%").limit(10)
  end

  def apply
  end

  def show
    @project = Project.find(params[:id])
    @favorite = Favorite.new
    @today = Date.today
    @finaldate = @project.finaldate
    difdate = @finaldate - @today
    @difdate = difdate.to_i
    unless Instagram.user_recent_media(ENV["user_id"], {count: 3})
      @users = ""
    else
      @users = Instagram.user_recent_media(ENV["user_id"], {count: 3})
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to root_path
  end

  def pay3
  end

  private
  def project_params
    params.require(:project).permit(:title, :finalprice, :finaldate, :description).merge(user_id: current_user.id)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:follower_id])
    current_user.follow(current_user, @user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).follower
    current_user.unfollow(current_user, @user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :following, :follower]

  def show
    @favorites = Favorite.where(user_id: @user.id)
  end

  def following
    @users = user.followings(params[:id])
    render "show_follow"
  end

  def follower
    @users = user.followers(params[:id])
    render "show_follower"
  end

  private

  def find_user
    user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/common/_courses.html.haml
#rightContent
  %section
    %h3#returnTitleText.returnTtl 支援するコースを選択する
    .anoInfo
      %p このプロジェクトは目標金額の達成有無にかかわらず、サポーターがプロジェクトに支援を申し込んだ時点でプロジェクトの成立（売買契約の成立）となります。
    #return
      %section.kakusectionRight
        .lefth4RightBase
          %h4.lefth4Right
            9072円コース
            %span.abstractSpan
              (税込)
          .lefth4RightNum
            %p 残り19個
        %a.ProjectDetailInRight
          %h5.lefth5Right 【スーパー早期特典40％OFF】サイフォングランデ１個【3モデルの中から選べる】
          .photoSectionUp
            %img.lazy{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/project/2354/return_2354_20241_280_165.jpg" }
          .detailTextRight
            ■スーパー早期サポーター限定リターン  限定数30個
            %br
            %br
            ■サイフォングランデ×1個  40%OFF
            %br
            ［一般販売予定価格15,120円（税抜14,000円）］
            %br
            %br
            ■モデルは下記3種類の中からお選びいただけます。
            %br
            "---------------------"
            %br
            ・ティアドロップ（涙型）
            %br
            ・ボール200（球型）
            %br
            ・フィッシャーマン（集魚灯型）
            %br
            "---------------------"
            %br
            ■仕様
            %br
            ・口金：E39
            %br
            ・消費電力：7W
            %br
            ・明るさ：白熱電球25W相当
            %br
            %br
            ※照明器具は付属しません。
            %br
            ※皆様のご支援により量産効率が向上した場合、正規販売価格が変更になる可能性もございます。
            %br
            ※デザイン・仕様は変更になる可能性もございます。ご了承ください。
          %p.detailAside02Uptext 11人が支援しています
          %p.detailAside03Uptext 2017年04月中にお届け予定です
        %aside.detailAside02
          %a.shienBtn このコースに申し込む
      %section.kakusectionRight
        .lefth4RightBase
          %h4.lefth4Right
            9072円コース
            %span.abstractSpan
              (税込)
          .lefth4RightNum
            %p 残り19個
        %a.ProjectDetailInRight
          %h5.lefth5Right 【スーパー早期特典40％OFF】サイフォングランデ１個【3モデルの中から選べる】
          .photoSectionUp
            %img.lazy{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/project/2354/return_2354_20241_280_165.jpg" }
          .detailTextRight
            ■スーパー早期サポーター限定リターン  限定数30個
            %br
            %br
            ■サイフォングランデ×1個  40%OFF
            %br
            ［一般販売予定価格15,120円（税抜14,000円）］
            %br
            %br
            ■モデルは下記3種類の中からお選びいただけます。
            %br
            "---------------------"
            %br
            ・ティアドロップ（涙型）
            %br
            ・ボール200（球型）
            %br
            ・フィッシャーマン（集魚灯型）
            %br
            "---------------------"
            %br
            ■仕様
            %br
            ・口金：E39
            %br
            ・消費電力：7W
            %br
            ・明るさ：白熱電球25W相当
            %br
            %br
            ※照明器具は付属しません。
            %br
            ※皆様のご支援により量産効率が向上した場合、正規販売価格が変更になる可能性もございます。
            %br
            ※デザイン・仕様は変更になる可能性もございます。ご了承ください。
          %p.detailAside02Uptext 11人が支援しています
          %p.detailAside03Uptext 2017年04月中にお届け予定です
        %aside.detailAside02
          %a.shienBtn このコースに申し込む
      %section.kakusectionRight
        .lefth4RightBase
          %h4.lefth4Right
            9072円コース
            %span.abstractSpan
              (税込)
          .lefth4RightNum
            %p 残り19個
        %a.ProjectDetailInRight
          %h5.lefth5Right 【スーパー早期特典40％OFF】サイフォングランデ１個【3モデルの中から選べる】
          .photoSectionUp
            %img.lazy{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/project/2354/return_2354_20241_280_165.jpg" }
          .detailTextRight
            ■スーパー早期サポーター限定リターン  限定数30個
            %br
            %br
            ■サイフォングランデ×1個  40%OFF
            %br
            ［一般販売予定価格15,120円（税抜14,000円）］
            %br
            %br
            ■モデルは下記3種類の中からお選びいただけます。
            %br
            "---------------------"
            %br
            ・ティアドロップ（涙型）
            %br
            ・ボール200（球型）
            %br
            ・フィッシャーマン（集魚灯型）
            %br
            "---------------------"
            %br
            ■仕様
            %br
            ・口金：E39
            %br
            ・消費電力：7W
            %br
            ・明るさ：白熱電球25W相当
            %br
            %br
            ※照明器具は付属しません。
            %br
            ※皆様のご支援により量産効率が向上した場合、正規販売価格が変更になる可能性もございます。
            %br
            ※デザイン・仕様は変更になる可能性もございます。ご了承ください。
          %p.detailAside02Uptext 11人が支援しています
          %p.detailAside03Uptext 2017年04月中にお届け予定です
        %aside.detailAside02
          %a.shienBtn このコースに申し込む
  .buyForgetArea
    .buyForgetAlert
      %i.alertCheck_off
      %span 終了前にお知らせを受け取る
  .anotherLinkArea
    %ul
      %li
        %a.open_contact_window プロジェクト実行者に質問する
      %li
        %a このプロジェクトについて運営に聞く
  .anotherInfo
    %p 「Makuake（マクアケ）」は、実行者の想いをサポーターの支援によって実現するクラウドファンディングサイトです。このページは、 プロダクトカテゴリの 「【第2弾】デザインLED電球Siphon 船舶モチーフ「Grande」先行発売！」プロジェクト詳細ページです。
  .makuakeLike
    %img.makuakeLikeImg{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/project/2354/main_2354_310_174.jpg" }
    .makuakeLikeBase
      %p.makuakeLikeP \このプロジェクトが気に入ったら/
      .makuakeLikeFb
        .fb-like.fb_iframe_widget
          %span
            %iframe{ src: "https://www.facebook.com/plugins/like.php?app_id=1407034392847669&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FiPrOY23SGAp.js%3Fversion%3D42%23cb%3Df38e3eed7466f58%26domain%3Dwww.makuake.com%26origin%3Dhttps%253A%252F%252Fwww.makuake.com%252Ff284cc68b060988%26relation%3Dparent.parent&container_width=0&href=https%3A%2F%2Fwww.facebook.com%2Fmakuake&layout=button_count&locale=ja_JP&sdk=joey&send=false&show_faces=false&width=111" }

app/views/common/_create.html.haml
= link_to add_project_path(project.id), remote: true, method: :post, class: "goodBaseIn_tab goodBtnHero_jq_1-off" do
  %i.fa.fa-heart-o
  %span お気に入り

app/views/common/_destroy.html.haml
= link_to favorite_path(current_user.favorites.find_by(project_id: project.id, user_id: current_user.id)), remote: true, method: :delete, class: "goodBaseIn2_tab goodBtnHero_jq_1-on" do
  %i.fa.fa-heart
  %span お気に入り追加中

app/views/common/_favorite.html.haml
%section.projectBox
  = link_to project_path(favorite.project_id), class: "projectLinkttlSuccess" do
    .ttlNewIconBase
      %img{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/project/2325/main_2325_310_174.jpg" }
    %h2
      = favorite.project.title
  %aside.projectAside
    %a.projectThumb
      %img{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/user/regist2016/11/04/161190/main_161190_36_36.jpg" }
      %span マクロウ MACRW
    %a.projectTag プロダクト
  .projectFooter
    .projectMoney
      %dl
        %dt 集まっている金額
        %dd 1,000円
    .projectGage
      %p 231%
    .projectBottom
      .projectSupporter
        %dl
          %dt サポーター
          %dd 156人
      .projectTime
        %dl
          %dt 残り
          %dd 51日

app/views/common/_follow.html.haml
= form_for current_user.active_relationships.build, remote: true do |f|
  = f.hidden_field "following_id", value: current_user.id
  = f.hidden_field "follower_id", value: user.id
  = f.submit "フォローする", class: "btn btn-primary"

app/views/common/_follow_form.html.haml
- if current_user && current_user != user
  #follow_form
    - if current_user.following?(current_user, user)
      = render partial: "common/unfollow", locals:{ user: user }
    - else
      = render partial: "common/follow", locals: { user: user }

app/views/common/_footer.html.haml
%footer
  .footer__inner
    .footer-up
      .footer-up--left
        .footer__media--up
          %h4.footer__title プロジェクトを探す
          %ul.footer__listblock
            %li.footer__list プロダクト
            %li.footer__list ファッション
            %li.footer__list フード
            %li.footer__list レストラン・バー
            %li.footer__list#footer__list-technology テクノロジー
          .footer__listmore
            more >
        .footer__media--down
          %h4.footer__title プロジェクトを掲載する
          %ul.footer__listblock
            %li.footer__list プロジェクト How To
          %a
            = image_tag "//cdn-m.makuake.com/rev_2017/01/11/154710/img/footer/footer_bn_apply.jpg", class: "footer__bn--pj"
      .footer-up--center
        .footer__media
          %h4.footer__title MENU
          %a
            = image_tag "//cdn-m.makuake.com/rev_2017/01/11/154710/img/footer/footer_bn_store.jpg", class: "footer__bn--store"
          %ul.footer__listblock
            %li.footer__list ヘルプ
            %li.footer__list プレスリリース
            %li.footer__list お問い合わせ・取材受付
      .footer-up--right
        .footer__media
          %h4.footer__title
            オフィシャルアカウント
          .footer__faceblock
            %iframe{ src: "https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fmakuake&tabs=timeline&width=340&height=350&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=true&appId" }
          %ul.footer__snsblock
            %li.footer__snslist#footer__snslist-tw
              %i.fa.fa-twitter
              %p.sns#tw Makuake_caをフォロー
            %li.footer__snslist#footer__snslist-line
              %i.fa.fa-
              %p.sns#line LINE@
            %li.footer__snslist#footer__snslist-insta
              %i.fa.fa-instagram
              %p.sns#insta Instagram
    .footer-down
      .footer-down--left
        Copyright © CyberAgent Crowd Funding, Inc. All Rights Reserved.
      .footer-down--right
        %ul.footer__listblock--side
          %li.footer_list--side 運営会社
          %li.footer_list--side 利用規約
          %li.footer_list--side プライバシーポリシー

app/views/common/_header.html.haml
%header#header
  #headerin
    = link_to root_path, id: "header-logo", class: "siteId" do
      = image_tag "makuake.png", class: "makuake"
    = form_tag "/projects/search", method: :get, id: "header-search" do
      %input.header-search__input{ type: "text", name: "keyword", placeholder: '"まだここにない"を手に入れよう'  }
      %input.header-search__submit{ type: "submit", value: "" }
        %i.fa.fa-search
    %ul.header-nav.clearfix
      %li
        = link_to "探す", search_projects_path, class: "link01", id: "link"
      %li
        = link_to "始める", new_project_path, class: "link02"
      - if user_signed_in?
        %li
          %img{ src: "//cdn-m.makuake.com/rev_2017/01/10/134526/img/header01/icon_mail_24_01.png" }
        %li
          %img{ src: "//cdn-m.makuake.com/rev_2017/01/10/134526/img/header01/icon_bell_01.png" }
        %li
          %image#user_image.user_image.link03After
      - else
        %li
          %a.link03#link Makuakeとは？
        %li
          = link_to "ログイン", new_user_session_path, class: "link04 btncol_03"
        %li
          = link_to "新規登録", new_user_registration_path, class: "link05 btncol_04"
  #myMenuBox
    -if current_user
      %ul.headerMyIconClick{ style: "display: none" }
        %li.mypage
          = link_to user_path(current_user.id), class: "myLink01" do
            .mypage_main
              %img.user_image/
              %span マイページ
        %li.help
          %a.myLink02 ヘルプ
        %li.logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "myLink03"

app/views/common/_project.html.haml
%section.projectBox
  = link_to project_path(project.id), class: "projectLinkttlSuccess" do
    .ttlNewIconBase
      %img{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/project/2325/main_2325_310_174.jpg" }
    %h2
      = project.title
  %aside.projectAside
    %a.projectThumb
      %img{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/user/regist2016/11/04/161190/main_161190_36_36.jpg" }
      %span マクロウ MACRW
    %a.projectTag プロダクト
  .projectFooter
    .projectMoney
      %dl
        %dt 集まっている金額
        %dd
          = project.currentprice
          円
    .projectGage
      %p 231%
    .projectBottom
      .projectSupporter
        %dl
          %dt サポーター
          %dd 156人
      .projectTime
        %dl
          %dt 残り
          %dd 51日
  .pageBase

app/views/common/_projectrecently.html.haml
%section.projectBox02
  / = link_to project_path(), class: "projectLink02"
  %a.projectLink02
    %img{ src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/project/2346/main_2346_230_129.png" }
    %h2
      = project.title

app/views/common/_side.html.haml
#projectssideNavi
  = form_tag "/projects/search", method: :get, id: "search_form", class: "findForm" do
    .findFormBase
      %input#keyword.findFormBaseInput{ type: "text", name: "keyword" }
      %input#start_search.findFormBaseSubmit{ value: "検索", type: "submit" }

  %dl.sideNaviOne
    %dt.sideNaviTitle.sideIconSupt プロジェクトを探す
    %dd
      %a 募集中のプロジェクト
    %dd
      %a 募集が終了が近いプロジェクト
    %dd
      %a 新着プロジェクト
    %dd
      %a 支援金額が多いプロジェクト
    %dd
      %a あと一押し!プロジェクト
    %dd
      %a ストア一覧
  %dl.sideNaviOne#accountinfo
    %dt.sideNaviTitle.sideIconSupt カテゴリーから探す
    %dd
      %a プロダクト
    %dd
      %a ファッション
    %dd
      %a フード
    %dd
      %a レストラン・バー
    %dd
      %a テクノロジー
    %dd
      %a コスメ・ビューティー
    %dd
      %a アート・写真
    %dd
      %a 映画・映像
    %dd
      %a アニメ・マンガ
    %dd
      %a 音楽
    %dd
      %a ゲーム
    %dd
      %a 演劇・パフォーマンス
    %dd
      %a お笑い・エンタメ
    %dd
      %a 出版・ジャーナリズム
    %dd
      %a 教育
    %dd
      %a スポーツ
    %dd
      %a スタートアップ
    %dd
      %a 地域活性化
    %dd
      %a 社会貢献
    %dd
      %a 世界一周
  %aside.Security
    %h2 セキュリティについて
    %p 当サイトはSSL暗号化通信に対応しておりますので、入力した情報は安全に送信されます。
    %span
      %a#aa
        %img{ alt:"グローバル認証サイト", src: "http://s3-ap-northeast-1.amazonaws.com/static.makuake-ca.com/upload/project/2233/main_2233_464_261.jpg" }

app/views/common/_status.html.haml
- if current_user
  = link_to following_user_path do
    %strong#following
      = user.following.count
    フォロー
  = link_to follower_user_path do
    %strong#followers
      = user.follower.count
    フォロワー

app/views/common/_unfollow.html.haml
= form_for current_user.active_relationships.find_by(follower_id: user.id), method: :delete, remote: true do |f|
  = f.submit "フォローをやめる", class: "btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Makuake
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"
  %body
    .wrapper{ style: "min-width: 960px" }
      .alert.alert-warning{ role: "alert", style: "background: #ffe600; text-align: center;" } ログインに成功しました
      / .alert.alert-warning{ role: "alert", style: "background: #ffe600; text-align: center;" } ログアウトに成功しました
      = render partial: "common/header"
      = yield
      = render partial: "common/footer"